# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('code_color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='')),
                ('main_image', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField()),
                ('power', models.IntegerField()),
                ('drive_type', models.CharField(choices=[('1', 'Full'), ('2', 'Front'), ('3', 'Rear'), ('4', 'Cardan'), ('5', 'Belt'), ('6', 'Chain')], default='1', max_length=2)),
                ('petrol', models.CharField(choices=[('P', 'Petrol'), ('D', 'Diesel'), ('G', 'Gas'), ('GP', 'Gas/Petrol'), ('O', 'Senior')], default='P', max_length=2)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Color')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarModel'),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Image'),
        ),
        migrations.AddField(
            model_name='car',
            name='specifications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Specifications'),
        ),
    ]
