# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20171026_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='specifications',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.Specifications'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, upload_to='all_img'),
        ),
    ]
