# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20171029_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='specifications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Specifications'),
        ),
    ]
